<?php

/**
 * @file
 * Contains challenge4.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function challenge4_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the challenge4 module.
    case 'help.page.challenge4':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Challenge #4') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function challenge4_theme() {
  $theme = [];

  return $theme;
}
